#include <iostream>
#include <string>
#include <vector>
#include <utility>
#include <cmath>
#include <sstream>
#include <regex>



bool searchFrom(const std::vector<std::vector<char>>& grid, int x, int y, const std::string& target, int dx, int dy) {
    int n = grid.size();
    int m = grid[0].size();

    for (int i = 0; i < target.length(); ++i) {
        int nx = x + i * dx;
        int ny = y + i * dy;

        // Check boundaries
        if (nx < 0 || nx >= n || ny < 0 || ny >= m || grid[nx][ny] != target[i]) {
            return false;
        }
    }
    return true;
}



int main(){

    std::string s =  R"(SAXXAXMMSSSSSXMXMAMXSXMAMAMXXXAMXAXXMXMAXSXMMAMXXXMSSSSSMSSSSSSMSSMMXSAMMMMXSAMXSMMMSASASMXMASMMXSSMXSAMXSAMXMMXXXAMAMXMASXSSMSASXMXSMMMMXXM
                        MASXMSMAXAAAMMMAMAMSAMSXSAMSMSMMXMSSMMSAAXASAMSAMXAAAMAMXAASAASAAAASMMASMAAAMXSXAMAASXSASXMSXMASAXAAAAASAXAXAXMMSXMASMMMMSAMXAMMXASXXAAMMMSM
                        MAMAAAMXMMMMMAMAXASAMXAAMXAXAAXMAMXAAAMMXMAMAXSAAAMMSMAMMMXMMMMMMMMMAAAMMMMSSXXAMMMMXMMAMXAXASMMMSMMMSSMXSMSMSMAAAMAMAAMAMXMMXMASMMMSSMMSAAX
                        MXSMMMSASXSSSSXSXXMAXMMSMMSMSMSMMSSSMMXASMSMXMSXSXXMAXAXXMXSXSASMSMSSMSSXSAMMMMSXSXXXAMXMAXSMMAAAAAAXXAMMAXAAAMMMXMAMSMMAMMMSXMAAAAAMAAAMSSS
                        SMMMAXSXSAAAXAAXXXSAMXAAAXMXAAAASAMXAXMASAXASXMAXXMMMSXSXMSMASAXAAAXMAAXXMASAAMAXAAAASMSMSMSASXMSMSMMSAMMXXMMMSMXAMMXXXSASAAAAMSSSMSSMMMAAXA
                        XAAXXASASMSMMMMMAXASAMXSAMXSMMSXMASMMMMMMXMMAASXMASMXSAAASAMAMMSSMSMMMMSMMXMXXMMMMMMMMAAAXAXMSXAAXAMASMMSMMSAAXXSXXSASAXAMMMMSMMAMAAAMMXMMSM
                        SSMXSAMAMXXAMXAMMMAXXXAXXAMXXMMMXSMMMAAAMMSSSMMAMAMSAMMSMSAAXSAAAMXXXMAXAMXSSSMXXXAAXMSMSMMMXSMMMSXMAXAAAMASMSSXMAXMAMMMSMMMXXMMAMMSMMSAAXAX
                        XAAMMMMXMAXAMSSSXMSMMMSMMSAMXMAMMXAXMXMXSAAAAASAMXXMXMXAXSXMAMMSSMMASMMXMMAXAASXXMMSMAXXXMXAXXAMXMMMSSMXMMAXMXXAMMMMMMSAMAMSSSXSXSAAAASXSSMS
                        MMMMASMSMMSMMSMXMAXAXAMAAMAMXSXSAMMMSMMSMMSSMMXAXSMSMXSMXMAMMXAMXAXMAXAASXMMSMMSAAAAXSXSXAXSMSXMASAMXAAASMSSMMSMASXAAAMASXMAAAASAMMSMMSAMAXS
                        MSSSMSAAXAAMMXXXXXSMMSSMMSAMAMAMXMAAAAXXAAAXASXSMSXMAXXXXXAMXMSSSXMASMSMSASAMAASMMXSXMAMAMMXAMXSXMSMMMMMSAAAMAXXAAMMSSMXMAMMSMSMAMMAMXMASMMS
                        XAAAAMMMMSSSMMMSMMAMMAXXXXXMAXAMMSMSSSMSMMSMXMAMASXXXMAMMSXMAMXAMMSXMAXASAMASMMSXMXXAMXMAXAXMSMAMXXMAXSMMMMMMSSMSSXXAXXMAMMAMXMMAMXAXXSMMMAX
                        MMMMMMAXMAMXMASAXSASMSSXSAMXSSMXAAMAAXMAXMAMSMMMMMASXMXXXAMXASMAMXSASMMMMMMMMAMXMSAMAMSSXSMMMAMXSASASMSAXXXXAXXMAAMAASASXSMXXAMMSSSXSASXMASM
                        XAAMMSMSSSXMMXMXMSASAAXMASMXMAAMSMMSSSSSMMMXXAXSAMXMXXAMMASMMMMMMXMAMAMXAMAMSAMMAMXSAMAMASAMSMMAMMSAMASMMMXMXMMSMSMMSAMAAMMSSMSAXAAASMMAAAXA
                        MSXSAAAAXAAMSSMMMMMMMMMSMMSAMMMMXAXMAMAAXXMASMMMSMSMXMXSMAMAAXMASAMAMAMSASAMMAMAMXASASMMAMAXAXMXSXMAMXMXAAXMMXAAXAXXAAMMSMAAAAMMSMMMMASMMMAS
                        XAAMXMSMMSMMAAAASAMAXMASAASXSXXMSMMMAMSMMAMXXXAMXXAMXMAMMSSSMMSAXMMAXAXXXXMSMAXSXMXMMMXMAMMMASMSMXXSAMXXMSAMSASXSMSSSXMAXMMSXMMAXXXXMAMSAMXX
                        MMSMMMAMAAAXSSMMXASMSMAXMMSMMMMMAAAXSXMAXMMAMSSMSSSSSMASXMAXMXMXSAXSSXSAAMXAMMMXASASXSSSMSAXAAXAMAMMAXMASXXXAAXAAAAXAMMMSXMMXAMSSMSMSMMSMMSS
                        XAAMXSAMSSMMMMAMSMMXAMXSXAXAAAASXSMXMASMMAXAMAMXXAAAXXMMAMSMSAXMAMAXAMMMMXSASMAXMSASAAXAXSXMMSSSSXXSXMMMAMSMMSMSMMMSMXSAXMAXMMSMAAAXXAAMAMXX
                        XSXSAMAMMMAMXAAMAMMSMSXAMMXSMMMSAXMASMMMSMMSMASMMMMMMMMSSMMASAMXMASMAMXAAXMAMMSMAMAMMMMSMSMSMAAMXMXAXXAXASAAXXAMASAXXAMASMMSAXAMMMMXMMMSSMMX
                        MMAMXSMSASMSMSMSXSASXMAMXMAXMXMMMMMAMAAXAXAAMAMAMSMSMSMAAXMMMMXAXAXSAMSMSXMXMAXMXMXMASXMAMAAMMSMMAMSMSMSMSASXMAMAMMSMMMAMAXAXSMXSASXSMXMAAXX
                        XMAMAAXSASAMAAXXMMMSAXAXAMXSAASAMXMMSSMSXSSXSSMSMAAMAAMSMMXSAASMMSMMXAXMAMSMMMSMMMMMAMMMAMSMSXXXAXAAAAXAAXXXMXMMXSMXMSMMSXMMXXMASXSAXMAMSMMA
                        SXSSMSXMAMMMSMSAMXASMMMSMMAMMMSASXSAAAAMXMXAMXXXSMMMSMXAMAMMMMAMXMASMMXMSMMASAMXAAAMASMSMMXMMXMMSMSMSMSMSMSMSAMXMMMMXAAXXAXXSASASXMAMSAMASXM
                        SAMXMMMMMMXMXXSXAXMXMAMAAAXMAXSAMAMMSMMMASXXXXXMASXXAMSSXSAXAMMXMXMMAXSMXAXXMASXSSSSMMMMMMSASAXAAMAXAAAXAXMAMMSXSASXSSSMXMAXSAMASMMMMXASASXS
                        MXMASAAAAMAMMMMSSXMAXAXSSMSMMMMXMAMXMAXSMSXMXMASAMXSMXAMXMASMSMAXSXSSMSAXSMMSXMMAMAMAAAAAASAAAASASMSMSMMMSMSMAAAMASAXAAAAMMMMMMMMMAAXSMMASAS
                        SASXMMSSMMASASAAMAMAMXMAAMAAMAAMSASAMSXSXSASXSAMASMMXMAXXXAAMAMMXSAAAAMAAXAASAMMAMXMSSSMSAMXMXMMAMXAMAXXXMAMMMMSMMMMMSMSXSAXAAMAAMSXXAXMAMMM
                        SASXSAMXMSAXAMAXSSMAXSAMXSSSMMXMSASXSMASASAMMMXSSSMSAXMAMMXMSXSMAMMMMXMMMMAMSAMSSXSAMAXAMXMMSMXXMAXXMAXXMXMXXMAXAAAXAXXMXSASXSSSMXAMXSMMASMM
                        MAMAMASAMXAXSMSMAAXSXXAXAAXAAXSAMXMMAMXMAMAMASAMXMAMSSMSMAAXSASMAMAXXAXXMASMSAMXAAMAMAMXMAAXMAMSASXSMSSMMAXMXMSSSMSMXSAMAMAXAAMXMSAMAMXSAXAX
                        MMMSMAMASMMMXAXMXMMMMSMMASXSMMSMMSMSXMASAMAMSMASXMAMMMAAASXSMAMMMSASMMSXXXXAXAXMMMMMMMSSSMSMMMMSAMAAXAAASXSMAAXAAAMAAXAAAMMMMMMAMSAMXSAXMSSM
                        XXAXMXMAMAXMMMMMAMXXAAASAXAAXXXMASXMXSASMSSXMXXMAXMMXMSMXAMXMAMAXAMAXSAMMSMXSMMSMSAAAXAAAMXAMAMSAMXMMSSXMAAXMSSSMMMMMXSSSXSAXAXAXXAMAMMMMAMA
                        SMSSMSASMMMXAXAXAMAMSSXMMMSMMMXMASASXMASAAMAMSMXMMXSSMAMMAMSSMSXMAMSXMAMAAMAMXAAXMXSXXMSMMSMSAXSAMXMAXAMMMMMMXAAXXXAMAAAAASMSMSMMSAMXXAAMASX
                        AXXAAAMAAAMSMSMSMSMMAMXAAMAAXMXMSSMMXMAMMMSXMAASXSAAASAXSAMXAMXMMXMMASAMSSMXSMMSXSAXAMMMMXAASMMXXMAMXXMAAXASMMXMMSMAASMMMMMXAAAAXMAMSXSXSXSX
                        MXMMMMXSSMMAXAMAMAMMMSXSAXSSMMAXAXXXXMMXSAMAMXSAAMMSMMMMSASXXMAMXSASAMAMAAXXXAMAAMAMXMAAXMMXMSAMXSSXSASXSAAAXMMSAXMSMXAASXXSMSSSXXMMMAXMMXSA
                        XXMAMXXXMASMMMMASASMXXMASMXAASMSMMSMMMSMMMSMMMMMXMXAXXMAMMMMSMMMASAMMMMMMSMXMMMMSMAMASMSMXXMAMMAXAAASAMAAMSMAMXMAXXXMSMMMMAMXAMMMSMAMAMAMAMM
                        MMSAMXXMMMAAASMMSASAMXMAMXXXMMAAXAAAAAAXMAXMAAAXMSXSMMMSSMSAMASMAMSMAASAMAXAAASXMMASXSXAAMXSMSASAMMMMMMXMMMMMXAMAMSXMASAAAAAMAXAAAMXMAMAMASX
                        XASMSMSMASMXMXAXMAMAMMSMSASMSMSMMSSMMSMSMAXSMMSMAXMAAAAXXMAXMAMMAMAMSMSASASMSMSASXXMASAMSSMSASMAAXMXAAXAMXXASAMMAMMASAXSSSXSMSSMMSSMSSSMSASX
                        MXSAAAASMSMXXMAMSMSSMAAAMAMAAXMAMAXAXMASMMXSAAXAMMMSSMSMMXSAMAXXAXMXMASAMXSAXMXAMXSMMMSMAXAMAMXMAMXSMSXSSMMASAMSXMSAMMXMXMAXAMXMAAAXMAAXMASM
                        XMXMMSMSXMAASXMMSMAMMSMSMSMSMMMAMASMMMSMAMAXMMMSAMAAXMXMSAMASASXSSXMSAMXMASAMSMAMAXAMAXMXMSMAMMXMSXMAMXMAXXAMAMXMAAAXMAXAMXMAMAMMMMMMMMMSASA
                        XXAMXMMXMMMMXAAAXMAMMXAAAAAAXAMAMXSXXXAMAMMSSMAXAMSSMSAMMASXMAMAXAAXMSSXAAMAAXSXMMSAMSSSSMAMAXXASMAMAMASAMMSSXMAMXXMMSMSSMMMMMSSSXSAAMXXMASM
                        MMXSAMXAMXAAXXMMSSSSMMMMSMSMSSXMSMSASXMSXSAAXMASAMXAXSAMSAMXMSMSMMXMAAXAMXSMMMMXAMMXMAXMASMSSSXMXXAMAXXMXMAMMAMXSMXAXXMAMXAAASXAAXSSMMAXMXMX
                        AAXSASMMSSMSXSAAAMMAMSSMXXMMAMAAAAXASAXAXMMSMXMAMSSSMSMMMMSAXAAMAXAMMMSXAMXXAAMSSMSAMMSSMMMAAAMSMSSSXXXAXMXXXAMSXAMSASMSSXSMSMMMMMXAMSMSMSAS
                        MSXMASXMAAMAASAMMMXAMXAMSMMMASMMMSMAMMMSMMAXMASAMXAAAXXAXMMMMMSMXMXXAXAMXMASXSAAAASAMXMAASMMMMMAAMAXMASMMMMSMMSXASAMAXXMAMXSMMSSSMSMMAAAAMAM
                        SMXMAMAMSSMMMMXMASXSSSMMASXMASAMXXAMAXAAXMAMXAMMMMAMMMSSSMMSAMMMSMMSXSMAAMXSAMMMMMMAMMSSMMAMXXSMSMAMSASAAAAAAXAXMXAMMMMMXXMASAAAAASXXMSMMMAM
                        AAAMASXMAAAXSAMMXMAXAAMSASXMASAMSMXMXMXSSMSSMXSAAASAXXAAAAASASMAAAXSASASXSMMXMASAMSAMXAAMSAMXXXAXMAXMAXXMMXSSMMMXSAMXAXXXXMMMMMMMMMMAMAXASAS
                        MXMSAXAMSSMMXAMXSMSMMMMMXSAMXSXMASAMXSAXAMAAMASMMSXMXMMSMMMSMMMXMMMMAMAMASAMASXSMMMASMSSMSASXMMMMMSSMSMSMSXXMASAMXAMSSSMMSMAAXXXSAMAMSASXSAS
                        XMXMMMXMMAMXMXMAXAXASMMMASAMAMASMSXSAMXSXMSSMMSSMXXMAMAAASASAXMASMMMAMAMXMAMASAMXAMSMMAMASAMXAAMAXMAAXMAAMMMMAMMSXMMXXAMXAMMMMXMMAMSAMXMXMMM
                        MMAASXSSSMMAASMMMSMAMXAMASAMXSAMXMMMMMXMAXAAAAMAXMASXSASMMASAMMAXAASASASASXMXMMMMSSMASMMMMMMSSMSMSSMMMSMSMAAMXSAMMAXSSMMSMSASMSMSAMXMXMMXSAM
                        ASMSMAMAMXMXSXAAAAMAMXXMASAMXMASAMASMXSSSMSSMMSAMSMMMAMXAMMMMMMSMSMSASMSMSXSAMXMAMAXAMXMXASAMXAAAMXXXAAXAMSSSXSAXSAMMAMAAMSASAAAMXMXXXMAAMAS
                        MXMAXXMAMMXXXMSMSXSASXSMAMAMAMXXAXSAMXMAAXMAAAMAXAAAMMASMMSAXXXAAMAMXXXMAMMAMSMSMSAMXXAASXSXMASMMSMMMSSXMAXAXMMMMMAXSAMSSMMAMMMMMMSAMXMMXSAM
                        MAMAAMSSSMXSXAXMXMMAMAMMSMSMSXMSAMAMSMMMMMSXMMSXSSSMSAMXXASXXXAMXMXMMAMXMSAAXAAAXMAMXMMMSAMMSAMXXAAAXMMMXMMMMXAAAXMMSAMAMASMMMMSSSMAAMSAMXAA
                        MAMXSAAAAXASMXMASXSSMAMAXAAAXAAMAMXXMAXASASAMAXAMXMASMXSMMXXMXMXMXXSSMXAXAXASMMMMSAMXMMASAAAMAXMSSSMSAMASXAAAMSXSMSMSAMXSAMXAAAXMASXMASMXSXM
                        XAXSMMSSSMAMMMMMMMAXMXXAXMMMMSXSAMSMSSMAMASMMSSSMSMAMXAXAAMSSSMAMXMAXMSSSMAXMXSXMSMSSSMASXMASMMMAAAAXXMASMSMXXMAXAAASXMAMMMSSMSMSMMMMAXAASAS
                        MSSXAAMAMMSMSAAAAMMMMSMMXSAXMAXXASXMAXMXMAMXXAAXXXMMSMMSMMSAAXSXMAMAXMAMAXMXMASAMXAAAAMAMAXMAMXMASMMMSMXSXMASASMSSMXMMMMSMMAMAAAXXAXMAXMXMAM
                        XXAMMMSAXXAASMSXSMXMAAAAAXMXSMMXXXAXAMMXMASXMMSMSSSMAAAAXXMMSMMMSXSMSMASXXXMMMSXMSMMSMMAMXMMASMMAXXAAXAAMAAMAAAXXASXMSMAAMMAMSMSSSSSSSXMMMSM
                        XXAMXAMMSMMXMMXXXMAMXSSMSXSAMASASXXMSMMASASASXXAAAASXMMXMSAMXAAXXXAXXMAMAXMASAMAXXXXAASXSAAXAAXMASXMSSMMSAMAMSMMSAMXMAMMSXMAMXXMAAMMAMASXAAA
                        SMMMXMMASXMXAASMMAMSAMXMAAMASAMMAMXXXASASASAMXMMMSMMXASAMSAMSSMMMSMASXSSMAMAMASXMMSSMXMASXSMSMXMASAAAMAAXASXMAMAMXMXSMSXAAMSSMASMMMMASMMMSSM
                        XAAXSAMASMMSMMSASAMMASXMMSMXMMMXAMMMSXMASXMAMXAXAXMXSSMAXSAMXXAAAAMMXAMXAAMAMMMMASAMXAMMMMMAAXXMASMMMSMMXMMMXAMSAMXXMXMMSSMAMMAMSXXMAMAXXAXX
                        MXMXMAMASAAXAXSXMASXASAMXMMSAMXSAMAAAXSAMXSSMXSMMSMAMMSSMMXXXSSSMXSSMSMASMSSXSASXMASMMXSAAMSMXMMXMXMASMMASAMMXMXXSXMSAXMAMXMAASAMXXMMSMMMMMA
                        SSSMSSMMSMMXMMMASXMMMXMXAAMAXSASASMXSXMAXMAXMAMASXMASAAXAMSMMMAXAAXAAXAXMAXMASASASMMMAAMMXMXXASMXMXMASASASAMXMASMSAAMMSMXXAXXMAMAMXXAAMAAXAS
                        XAAAAAAAMASXAAXXAMXAAAXSMSAMSMASAMAAXASMSSMMXASXMAXAMMMSXMAAASAMMXMMMMMMMSMMAMAMMMXAXMMSSSSMMMMAASASAMXMASAASMMSAMMMMSAMXSSSSXSXMXSMSXSSSSMA
                        MSMMSMMMXAMMSSXMSSSSSMXAXAMXSMAMMMMMXAMXAMAMMXSXSMMMXSAMXSSSMMASXMXASASAAAAXXMXSASMMMSAXMAMXAAMSMMAMMSSMMMXMSAAMXMXSMSASAMMAXXMAMXAAAAMXMAMM
                        XMAMXASAMSSMAXASAMXAAXSAMMSAMMSXXSSSSSMMXSAMSMMAAAAXAMAMXXAXASAMAMSASASMSMSXXXMSASASAMMSMMMMMAMAXMMMSAMXAAAXSMMSAMXSASAMXMMSMSSSMAMMMMMASAMX
                        MSAMXXMAXXAMASXMASMMMMMAAXMXSAXSMSAMAAAXAMASXAMSMXAMMSAMXMAXXMAXAMMXMAMMMAMMMAAMXMAMSMXAAXAAAXSAMXAMMMSMMMMMXXAXASAMMMXMXMAMMAAAXAXXMASAMXSM
                        ASMMSXSXMSMMASASXMXAMXSMMXXAMXSAMMAMSMMMSSMMMSMXXXXMXSASXMASMSSMXSAMMMSXMAMASXXSAMXMXXSSSMMSXMAMXSMMSMAMSSSSSMXSAMASXMMSMMASMMMMMMXMSXXAXXMX
                        MXSAXMASAXXMMSAMMMXSXMXAMXMMSSMMMSSMAASAXAAMAMXXXSAMXSXXMASXAAXAXMMMAASAMXSXXAASXMMXMXMAMMMMASAMMASAXXAMAAXSAAAMMMMSAMSAXMAXXXAMASAMXMSMSMSM
                        SAMXMSAMSAMXMMXMASMMMMSXMASXSXMXMAMSMSMMSSMSSMMMMMASAMXMXMAAMMMXMAASMMSASAMXMMMMAMAASMMAMAASXMAXSAMMSSSSMMMSMMAXAAMXAXMAMSXSMSXSASASAAAAAAAM
                        MMMMXMAMMMAXXSMXSAMXAAMASASMMAASMSXSMAMMAMXAAAAXAMMXAMAMAMSMSMXSMSMSAASAMAMAMAXMASXMMAMXMXMSAMAMMASXMAAXXXMXMMSMSSMSAMXSMMASAAAMXMMMXSMSMMXS
                        XAAMXSAMXXSSMAAMMXMMSMSMMMSAMXMXAMAMMMMMAMMSSMMSSSMXSAAXAXAAXAAAMXXSMMXXMAMAXXSSMSASXMMMSMMSXMAMXMAMMMMMMXAAXAAAMAMXAMAMAXAMMMMMASXMMAMXXMAS
                        SSXSASAMMAMAAMSASASAXXAAAMSAMXMMXMAMXXSSSMAMAMAAAAMSASMSXSMSMMMSSMASXSSMSSSSSMAAASAMSXAAAAXSXSSSXMAXXXMAXMSMMMSMMAMSXMASAMXXXAAMAMAXMAXAAMAM
                        XXAMXSSMSAXAMXXAXAMAMSSSMMMASXMAASXSAAXAXMXMAMMXSAMMAXMAMXAMAXAMAMAMMAAAAAAAAMSMMMMMSMMMSSMMAMMAMMSSXMSSXMASMAMASXMMXMXSMMMXSMSMSXMMSXMSSMSS
                        MMXXMXMXSASMMMMSMSMAMXAMXAXAXAMSMSASMXMSMMSMASXXMMAMXMXMASXSAMXSAMASASMMMXMSMMAAMXMXMASAMMAMAMXXAAXXMMAAASASMASMMAAMSAMXAASXMAXXMASASAAMMAMX
                        AXAMMXMMMAMXAAAXMASXSXSXSMSMSAMXMMAMXSAXAMAMASMMMMXMASMMAMMMMMMMASASMMAAAAMMMXXSXAAXSAMAXSAMXSXSMSXSAMMMMMAMMMXAXMMMMASMXMXAMAMASMMASMMMMAMS
                        SSMMSAMAXMAMXMMMSASXMAXAAAAASXMMMMAMXMASMMXMASMAMAXSAMAMAMMAAAXXXMMXASMMMXSAMXMMXMSMMASMMXASXXAXAAASXSSSSMSMMMSMMMSASMMMXSXMMXSAMXMAMAAMXSSS
                        XAAASAMAXXASMMSAMMXAMAMSMMMXMMMAXSXSXSAMXAMMMSMSMSMMASMSMSSSSSSXMASMMMAMXXMAMMSAMMAXSMMMAMSMMMXMXMMMAXAAAAAAAMAMXXMASAAXASAMAXMASMMXSMMSAMAX
                        SMMMSXMASMMSAAMXMSSMMAXAMAXAAAXMXMMMMMASAASXASMMXMASAMAMMAMXXXAASMMAXSAMMXSSMXMAMXAXXMMMAMXAMXMMXXMMMMXMMSMSMSASAMMSMMMMASMMXXMXXAMAMMAXXMAM
                        MAMMMMMASAASMMMSAXAMMMSSSSSSSMSMSXAXMSMMMSAMXSASASXMASXMMXSXSMSMMASMMMMSXASAXXSSMMSXMASMMXMAMXAAAMASXMMXXXMXXMMMAAXAAAXMAXXAMMMMMSMASAMXSMSM
                        MAMAAXMAMMMMAMAMXMXMAXMMAAAAAAAASXMMMAMXXXMAXSAMXMMXMAMXAASXMAAMSASXAXASMMMMAXMAAXAASAMASMSSMSSSMSAMAXMASAMSXMAXXSSMSMXMMSMMSAAAAAMAMMMXSAAS
                        XSSSSMSSMSAXAMXSSMSSMSAMMMMSMMMSMAMSSSSSMMXSAMXMXXXMXMSMMXSAMSMMMASMMMMSASAXMSAMXMMMMASAMXAAAAAAAMASMSMMMAXAASAMMMAAAXSMMAAASMSMXXSAAXMAMSMS
                        AXAMXAAAASXSMXXMAXAAMSAMXXXXXAXXMXMAAMAAAAAMXSMMMMXSAAXAMXSAMXXXMAMAMAMXAMXSXSASMMXSSXMASMSMMMSMMMAMXAAMSMMSMMASXAMXMSSMSMSMMMXXAAMAMXMMXMSX
                        MMAMAXMMMMAAAASMSMSSMSXMXMSSSSXSSSMMSMSMMMXSAMMAMSASMSMSMMSAMMMXMXSXSASMAMAAAMAMAXMAXXSXMMAXAXAAAXAMSSSMAAMXASXMXMASXXMASAMXXSAMSSSMMAXMASXM
                        XSXMASMXMMXMMMSAMAMMAMMMMAXAAAASASXMAAXMMMMMMMXAMMASAAMMAMMXSAMMMAMXXAXXAMSMSMASMMMMMXSAXSXSSSSSMMSMMXMMSSMSXMMSMSXMXAMSMAMAXMAXXAAASXMSMSAM
                        XASMAMAAMXMSAAMXMAMMXMAAASMMMMMMAMMSMXMXAAAAAMMSXMAMXMSSMMMASASAMASMMSMSXXXAXXAMAAXXXASMMMAMXAMAMXMAMMMAMMXMAXMAMMAMSMMMMMMXMSSMMMMMXAAAMSAM
                        SMAMASMMSMASXSMMSXSAMSSSSXMAAMAMAMAXXXXSSXSSXSAXAMXSSMMMAAMMSAMMSASXAXAXSAMXMSMAMMMSMASXAMASMMMMXMSAMAMSXMASMMSMMSAMASAXASMXXAAXAAAXMXSMXSAM
                        XXMSASAAXMXMAMAXAAMAXAAMMMMSXSASMXSAMXXMXAMXAMASMMAXMASXXMSAMAMXMASMMMMMMXXAXAMSMSASAMXXXSAMAAAXAXMASMSAASASXASAAMASAMMSXSSSMMSSSSMSAAXMAMXM
                        AMXMASMMMSASAMXMXSXMMSXMASAMXSASASMSMSAAMXMMSMMMXMXXSAMSXSMASAMSMMMXAAAAXAMASMSAAMAMSAMXMMXXSSMSMXXAMXMXMMASMXMMMSMMMSMSAMMMAMAMMAMSMMMMASAM
                        XXAMXMAAASASASXMXXXMAMASASAMAMXMXMAMMAMMMXSXAAMMMSMMMMAMMSSMMXXAAAMXMSSMSXSASXMMSMMMMMSXMASMMMASMSMXXMXXXMASAMXAAAXAXAAMXMAMAMAMMAMXAXMXASAS
                        ASMSMSSMMMASXMAMASAMXMAMASAMMMMMMMMMMAMAXMASXSMAAAAXMMSMAMAMAMXMSMXAMXAMMXMASXXXXAXSAMXAMAMMAXMXAAASXMMMXMAMMMMMMXXASMMMSSSSMSXSSSSSMMSAASAM
                        MMAAAMXMXMMMMXAMMXMMMMMMASAMXAAMXMAAMAMXSMXMMAMMXSAMXAAMMSAMASMXMAMSXSAAXXMAMMXMMAMMAXSXMMSMSSXMMMMMAAMMAXASAMASAMSAAXSAAXAAXXAAXMXAAAAMXMMM
                        XMSMMMAXMASAXMXMMXSAMXASXMASXSXSASXSSXSAMXAXMASXAMAAMSMSASXSMSAMXAAXASXMSAMAMMXSAMSSSMSXMSAAXMASXMMSSSMSXSASASASAMASMXMMSMSMMMMMMMSSMMAXSAMX
                        SAMAMSAMAXSASMSXSAMASMAMXSXMAMASMSAAAASXMSXSMAXMMMSAXAXMASXSMMAASMMMMMMSAXMAMMASASAAXAXAXXMSMSAMAXAMAMAMASXMAMASAMMAXASAXXMXAAAAAXXXSAXMMAMS
                        XXSAMXAXSAMXMAAXMAMAAMAMMMMMAMAMXSMMMMMAXAXSMSSMMAMXMASASXMMAXAMXMAXAAXXMXMXSMAMXMMXMXSSMSMXAMXSAMXSAMAMMMASXMXSXMXMMXMASAMXSMSSSSMAAMMXSAMA
                        MMMMMSAMMMSAMMMMXAMXXSASAAAMAMXSASMXSASXMMXMAMAXMASMXMAMMAMSSMMXSSSSSSSXXXSASMSMSXSXMXAXAAMMXMMXXMASXSXSASAMASAMXSMXMASXMAMMXAMXAAMSMXAXMMXM
                        XXAMXAXXXASXSXMASAXMAXMMXSXMMXXMAXMASMXAAXAMSSMMSXSASMMASXMAMASAMXXAAAMAMXMASAAAMAAAXSAMSMMSXAMASMXMAMASAMASMMASAMMXMASASXMAMSMMMMMAMMSMSMSX
                        MSSSMMXMMMSASAMXAMXMAXSSMMXSAASMMMMASMSSMMXSXAXAMXXXMASMMMMXSAMASXMMMMMXSAMAMMMSMXMXMMXMMAASXSMMXMAMMSAMMSXMXSAMXSAXMASAMAMXSMXMASMMSAAAAAAX
                        XAAAMXAMXXMXMASMXMXMMSMAAAAMAMMAASMMSAAXAASXXMMMXMMSSMMAXXAMMMSMMMXAAXMASXSSSSXXMAMAMXSMMMMSAXXMASXSAMASXXXAXXSAMXMXMAMMSMMMMMSSMSAMMMSSMSMM
                        MMSMMSXSAMSSMMMMSXMASAMXMMSSMXMXMMAMXMASXXSAXMAXAMXMAASMMMMSAXAMAMAXSSMXSAAAAMAMSXMASAMSAAMMXMASASMMMSXMMMMASAASMXSASXSMAAXXAAXAMMMMAMMXXAXA
                        AXMAMXMAXSAASXAAMAAXSXXXAXMAMMSXXXAMMSMMXMMXMSSSMSAMMMMXMAASXMMSXXMSMXAXMXMMMMMAAXXXMXSAXMXXASXMMMAMXAAXAAXAXMAXXASASAMMSSMMMSSMMASMSSMASMMS
                        MMXXSAMAMMMSMSMSMSSMMAMSAXMAMMAASMMSXAXMMXAAXXMAASMMSAMASXXSMSXMMMXAMXSMSAXAXASMMSAMXMMMASMXXSXXXXXMMSMMSSMMSAMXMXMAMXXAXAXMAAAAMAXAAAXAMMAM
                        SAMMSMMASXXXXXMAMAAAMAMAASMMMMMSMAASMMMXAMSSSSMMMMAASXMASMAMXXAAMSMMSAXAXAXSSMSAAMMAMXAXMASMSXMASMSAMXXAXMAMXXMMXSMMMSMMSSMMMSSMSSMSMSMSSXSS
                        ASAAMASASXMXXMASMSSMMXSMSMAXMAMAMMMMASMMXXAAAAXXMMMMSXMXSMAMMSMMMXASMXSSXSXXAMXMMSMSMSAXSAAMMAMAAXMASMMSSSSMMAMAAXAXAAAAXAAXAAAXXAAAAMAXSAMX
                        MXSSSXMASASXXSAMXAAAAMXXAMAMMMSSXSAXAMAAXSMMMMSMSXAAXAMMSXXSXXMAMXMMAMXXMAMMAMSXMXAAMAAXMMXXMAMXXMMAAXSXAAMMMAMMXSAMSMSMXSMMMSAMXMMMMMSMXMAS
                        XMAXMMSXXAXAASMSMSSMMASMSSSMSMAAAMSMSMMSXMASMXSAMXMXSAXAXMSMAMMASAXMMMMMXMSSSMSAAMMMMMSMXXXMXMXSAAMMMSMMMSMAMASAMMXMAAAXMMXXXXXMAXAXAAMASMAS
                        SMSMMAMMMSMMMMASAMXMASAMXAXAAMMMSXXXAAXXASMMSAMMMMSAXMASMXXXAAXASXSAMXAMAXXAXASMMSMSAXMAXSMSAAASXMMSMAXAMXXMSAMMXMASMSMAASMSAMXSMSSSMMSAXMAS
                        XAMAMSMSAAASXMAMAMSXMMASMAMSMSXAMAMXXMMMMSAAMXSMMXMASMMMAAMMMSMXXAAXSXMSSSMMMXMAXMASXSMXMAASMMMSAMAAMAXMMMAMXXXXAXMMAXXXXAAXASMAXAAAMAMXSMAS
                        SXSAMXAMSSSMAMXXMMMAMSAMXMXXXXMASAMSMSAXASMXSAMASASXMMXMSXAXAAXAMSMMMXMAMXAXAXSXMMMMMXMAMMMMAMMMAMSMSSSMSMAMMMMSMXXMASXSAMAMMMXAMSSSMSSMMMAS
                        AASXXMMMXXAMXMSMSMSAMMXSASAMXXMAXASAAMAMXMAMMMSAMXXXAXMAMXSMXXSMMAAAAAMAMXMAMMAXSAXAXASAXAXXAMSMSMXAAAAASMSSSMAAMASMMAASAXSXMSSMMAAAXMXMXXAM
                        MMMMMXXSMXMMMXAAAAXMXSASXSXXMMMMMMMMSMXXSMSMAAMMSSSMMMSXMAMXSAAASMSMSXSMSSMMXAAMSSSMSXSASXSSSSXAXASMMMMMMAXAAXMMMAXAAMXMXMXAXAAAAMXMMMAMXMAS
                        MSAXSAMASAAAXMMSMSMXXMASXMASXSMSAXMAMXXSAMXAMXSAAXXAAAXAMXMAASMMMMXMAXMAAAMSMMMMXAXAAAMAMAAXMAMXMAMAXMAXMMMSMMSSMMSSMSAAAAMSMSXMMSAMASAMAAXA
                        SMMXMASAMMSMSAXMAMXXXMXMXMAMAAASMSAMXAXAMASAMAMMSXMMMSXSMAMMMMMMMAAMXMMMMSMXAMXXXAMMMSMSMMMMXMASMXMXSXXMAXAMAMAAAMAMXMMSMSAXXMASASMMMSASXSXA
                        SAMASMMMSAMASMMMAMAMSAAMAMASXMMMXXXMMSMSXMXXMXSMMASXMXAMMAMMAXAAXXMXSAASMXMMSMMMXSAXSXAXSXXXSAMXAASAMASMSMAXAMXMMMAMMXMXAMAXMSAMASXSASAMAMAS
                        MAMXSXAAMXMAMAASAMAMXASMMSASAAXXXMXSAXAMXMSMSAAAMAMAAXMMSSMSASXXMAAAXXMMMAMXAAAAXXXXXMXMMXMASASXSMSAMXMAXXSSMMSMSSSMSAAMMMAMMMMSAXMAAMXMXXAM
                        SSMMMMMMSMMSMMMSMMSMMXMAXMASMMMMAMAMMSMSMSAAMSSMMXSMMMXXAXAMASAASMMMSASXSSSSSSMSSMSMSMAASAMMMMMMAXSMMXMXMMMAAAAAMAAASXSAAMXMXAMMASMSAMXAMMMM
                        SAAMMAAMXAAMASAMMAMMMASXMMAXAMXAAMXSXMAAXSMMMXMMMMXMAAXMASMMXMMMMXAASAMXXAAXAMXXAAAAAXSASMSAAASAMXSXSXSXSSSMMSMSXSMMMAXMMSAMXAMMMMMAASXMXSAM
                        SXMMSMSSSSMSAMASMASASASMSMMSAMSSMSXXAMMMMXMASAMAAMASMSMAXXXMSMMMSMXMSAMXMMMMMMMMMSMSMXMXMASXSMMMXXMAXAMAMAAXAMMAAXSXMXMXXSASAMSMMSMSASAXXAAS
                        SXSXSAAAAXXMASXMMASAMXSAAAXXAMXAMAMMMSAASMSAMAXSASASMAAMMMSAAAXXAAAXSMMSAAXAAAAAXXAAXXXMSXSXMASXSSMSMAMXMSMMASMMMMAMSMMMMXAMMSAXMAXMASXMMSMM
                        MAXAMMMMMMASAMMSXAMMMMMAMMMSSXSXMMXAASMMMAMMSXMXASXSMMSASAMSSMMMSSXXMAAXMXMSSSSSXMSMSMMMMMSAMXAXMXAAXAXAXAXXXAXSXMMSAAAMAMSMMSASXSSMAMMAAAAX
                        MAMMMMMMAAMMMSASMSMSASMSXXXAXMSAMXMMMMAXMMMASAAMAMAMAAXXMAMXMAMAXAMXMMMSMSMXMMXMMXAXXAAAAXXXMSMSMMMMSMMMSSSSSSXMASXSMXMMXMAAXMAMXMAXAXMMMMSM
                        MXSAAAXSSSXSXMASAXAMASAXAMMMXAMAAAAMSSSMSMXASMMMAMAMMMSAMSMAXAMXSASMAAAAAASAMXASAMSSMSSSSSXAMSAAXAAMAMAMAMXAXMASAMXXXSMASXSSMMMMSSMMSMMASMAM
                        XAMXXMXMAAMMAMAMMMSMMMMMMMAMSXSAMXSXMAAAAXMXSAAXXSXSXMSMMXASMSSMSAMXSXSMSMMMMSAXSAMAAAAMAXMXAMSMMSXSAMMMMMMAMSAMXSMSMAMASMXAXXAAMAXXAASAXMAM
                        MSSMMSMMMMSSMMASXAXXMAXAXSXXAMXXXMXMMMMXMMXMXMMSMAMXAXMMSXAMAXAAXXMAMMAMXXXAAMAMMSSMMMSMXMMSMXMMMMAMAMSAMSSSMXMMAAAAAMMXSXSMMSMSSSMSMMMMSSSM
                        XMAMAAAMXAAAASAXMMXSMSXXMSMMASXMSMAAAAMSMMSMXMMAMAMSXMAAMMMMXSMMMMSAMXXSAXMMXSXXAAMAXMXMASAAXMAMAMXMAMMASAAAXMSMSMXMMXXAMMXAAXSAAXAAXASXMAXM
                        MSAMSSMMMMSXMMMSASMSAMMXXMASAMMMASXSXXMAAAAAASXXSAXAASMMSXXAAXAAMAMMSXSMMSMMMSXMMSSSMSASXMMMSMXMASMSMSSMMMSMMAAXAXMSSMMMSAMMMMMXMMSMSASAMAMX
                        MMXMXAMSSMMXXAXXMSASAMXSSSXMXSASAMXXMMSMSMMMMSAAMXSMAXAXAASMASXMSSMASXXAAXMXAMAMAXAAAXXSMSMMSAXSAMAAMMAMSMAMASXSXSAAAAXSAXXMMXSMMAMXMASXMMSS
                        XSASMMMXAASMMMXSAMXMSMXAAMXMSXMMASAXAXSAAAXSAMXMMAMXMXSMSXXAMAMXAXMASMMXMXMMXSAMAMXMXMASAMXAMMMMASMSMSAMXSASXMXAAMMXSMMMASXAMAMAMASXMMMMXAAA
                        SXAXASMMMMMAMAAMXMASXSMMSMSXSAXXMMXSXAMMMMAASXMSAMXSXAMXXAASMASAMXMASXAAMAMAMSXMXXXAXMMMSMMMMXXXAMXMASAMXSMSASMMSXSMMMAMAMMMMSSSMAMASMXAMMSS
                        MMSMMASXMSSSMMSSXXXAAXXXAAXAMSSXSMAMMSSSSSMMXXAAAXAMMXSAMXXMXXMXMAMAMMSASAMAXSMSXAXSSMSAMXMSSMSMXSAMAMASXSMSAXXAMMMAXXXMAXMAAXAXMXSAMXMSMMAX
                        XAXASAMXMXAAASAMMMMMMMMSMSMAMAMAASAXMAAXAAXXMMSMAMASMMMXMMXMXSAMXSMASAXXSXXMMSAMMMMMAAAAMXSAAAAAAXXMMSXAAMAMAMMXSASMMSMSASXMSSSXMAMXMAAAAMAS
                        MSSMMSSSSMSMMXAXMAAAMAAXXMAXMAXSASMSMMSMSMMMXAAXXSXSMAMAASMMASASAMMXMXSMMMSMAMXMAXASXMSSMXMMSSMMXSAMASMMSMAMAXMASAMXAAAMAMAAAAMASAXAXXMMXMXS
                        MAMXAMMAMAAAXSMMSMSMSMSMXMXXMSAMXXAXXMAMAXAXMSSSXSAMMASMSXAMAMAMASXMSAMAASAMXSASXSAXXXAMXXMXMXXAXSXMAXAXMASMXXSAMAMMSMSMASMMMXSASXMAMSAXSAMX
                        SAMMMSMAMSMSAMAAAXAAAAAMMMAMMXXMSMSMXMASXMSAMXAXMMAMSMSXMXSMMXXMAMXAMASXMMMMMSASASMSMMAXMMXAXXMMXMMMMSMXSMMMXMMAXXMAAAXXAAMXMXMASAMAAMAMSAMS
                        SASXSMMMXXAXAMMMMXMMMMMSAMSSMAASXAXAXSAMXMAMXMMMAMAMMXMASAXASAMMSSSMSAMAAXXAAMXMAMAAAXMMSASMXSASXSAAMAMXSAAXAMMSMMMSSMMMMSXAMXMASAMSSMSMMAMA
                        SXMXAMAMSMMSMMSMSSMMSXMMXXMAMXXXMSMMMMASXSXMSASMSSSMXAXMMMXAMMXMXAAAMMMXMMSMXSMMXMMMMXASMASAASAMASMXXXSAMMMSXSAAAXAAAAXXMAXMSXMAXAMXXAXXXAXA
                        SAMMXMAXAAAMAMSAAXMAMAXAMXXAMXSSSMMAASAMXSAASAAAAAAXSSMSASMXSXMMMMMMSMSAMXXAASAMASMAAXMMMAMXMMAMXMSSXSMASMMXAMXSMMMSSXMXMASMAMMXXAMSMXMMSMSM
                        SAMSMXSSSMMSSMMMMSMASXMSSSMAMSAXAASXXSMSAMMMMAMMMMMMXMASASAASMMAAXAAAAMMMSXMXMAMASMMSSMAMSSMXSXMASASXASAMAXSMMAXAXMMMMMMXMAXMSAXXAMSXMAMAMAM
                        SXMASAMAMXMAMAMAAAXASAAXAXMAMXMSMMMXAXXMMSSMSMXMMMMXXMAMAMMMMASXSSMMSSXMASASMSSMXXAAAAMMMMAMAXMMXMASXMASXXMMXMXSMMSAAAAMMMMMXMAXMSSMAMMSASMX
                        XASASXSSMAMASAMMSSSSSMSMAMSSSXMAMAMMSMSXMAMXAAAMSASAMMSMASMXSAMXXAXAAAXMASMMAAMMMSMMSSMMASMMSAMXAMAMAXAMMSAXXXMMMASMSSXSAAASMMSMMXAAXMASASXS
                        SXMASXXASXMASMSAAAXAMXAMXMAAMMSAXAXMAAMXMASXSMMXSASAXAXSXXAAASXMSMMMSSXXMXXMMMMAAAAXAAASASAXMASMSSMSSSXAASMMMMXAMXSAMAASMSMSAAMMMSXMMMXSAMMA
                        MAMAMXSMMSMMSAMMSSMSSSSSMMMSMASMSMSSMSMAMAMAXAMXMXMMMSMMSMMMMMMAXXXMMMAAXMASASMMSSMMSMMMAXXMXXXXAAAXAXAMXMAAAMMXSAMMMMMMAXXSMMSAAXAMAXAMAMXM
                        SAMAAXXXAXXMMMMAXAAAAXMMAAAMMMSAAAMXAMXXXSMMSXMXXXXAAXAASXXAAAXXMMSMAMXMMAAMASAMAMXMXSMMAMSMMMMMSMMMMMSXAXSSXXAXMXXMAXXMMMMXXAMMMSMMAMSSMMSX
                        SXSMSMSMSSSMASMMSMMMSXSSSMSSMAMMMSMSMSSSMXAXSASMSMASMSMMSASMSXSMSMAMASMSSSSSMSAMMMMMAASAMXSAAAXXAMAXAAMAXXAAAMSMMMSSMMMAAAASMMSAMXAAXSAAMAMS
                        MAXAXAAAAAAMAMAXXAXAAMMAMXAAMXSXXMASAAAAASAMSAMAAAXMAXMAXAMAXASAAAMSASMAAAAAASXMAAAMXMAXSAMXSSMSASMSMMSAMMMMMSXAAAXAAAASMSSXAASAMXMMSMMSMASA
                        AMMXMSMMMSMMSSXMSMMMSSMAMMSXMASMSMSMMMSMMMXAMSMSMSXMXMSAMXMXMXMSMSXMASMMMMMMXMASMXSAMXXMSAMXXMMSAMXAMXMASXSSXXXSMSSMMMMXAMXMMMSXMXXMXMSMMXSX)";


    std::vector<std::pair<int, int>> directions = {
        {0, 1},  
        {0, -1}, 
        {1, 0},  
        {-1, 0}, 
        {1, 1},  
        {-1, -1}, 
        {1, -1}, 
        {-1, 1}  
    };

    std::stringstream stream(s);
    
    std::vector<std::vector<char>> grid;
    std::string line;
    std::string target = "XMAS";
    int found = 0;

    while (std::getline(stream, line)) {
        std::vector<char> inner;
        for (char c : line) {
            if (!std::isspace(c)) {  // Skip whitespace characters
                inner.push_back(c);
            }
        }
        grid.push_back(inner);
    }

    for (int x = 0; x < grid.size(); ++x) {
        for (int y = 0; y < grid[0].size(); ++y) {
            if (grid[x][y] == 'X') {  // Start search only if the first character matches
                for (const auto& [dx, dy] : directions) {
                    if (searchFrom(grid, x, y, target, dx, dy)) {
                        found++;
                    }
                }
            }
        }
    }
    std::cout << found << std::endl;


    return 0;
}